---
language: php

dist: trusty

sudo: true

env:
  matrix:
#    - DRUSH_DEV=true  # TODO: Fix dev version of Drush install (or remove it entirely)
    - DRUSH_DEV=false

before_script:
  - sudo -E ansible/bootstrap.sh
  - cat behat_params.sh
  - sleep 3  # Give web server a chance to start
  - echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
  - curl http://localhost:8888

script:
  - make test-on-travis
