---
language: php

dist: trusty

sudo: true

env:
  matrix:
#    - DRUSH_DEV=true  # TODO: Fix dev version of Drush install (or remove it entirely)
    - DRUSH_DEV=false

before_script:
  - sudo -E ansible/bootstrap.sh

script:
  - make test-on-travis
