---
language: php

dist: trusty

sudo: true

env:
  matrix:
#    - DRUSH_DEV=true  # TODO: Fix dev version of Drush install (or remove it entirely)
    - DRUSH_DEV=false

before_script:
  - sudo -E ansible/bootstrap.sh
  # Debugging
  - cat behat_params.sh
  - ping -c3 localhost  # Give web server a chance to start
  - apache2ctl -S
  - apache2ctl status
  - curl http://localhost:8888/
  - curl http://127.0.0.1/

script:
  - make test-on-travis
