---
language: php

dist: trusty

sudo: true

before_script:
  - ansible/bootstrap.sh
  # Debugging
  - cat behat_params.sh
  - ping -c3 localhost  # Give web server a chance to start
  - curl http://localhost:8888/

script:
  - make test-on-travis
