---
- hosts: localhost
  vars_files:
    - ../group_vars/all.yml
  vars:
    - composer: "{{ (vagrant) | ternary('/vagrant/composer.phar', 'composer') }}"
    - behat_deps:
      - php5-curl
      #- openjdk-7-jre-headless
  tasks:
    - name: Install Behat dependencies
      apt:
        name: "{{ item }}"
        state: installed
      with_items: "{{ behat_deps }}"
      remote_user: root
      become: true
      when: vagrant
    - name: Download Selenium
      get_url:
        url: http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar
        dest: "{{ root }}/selenium-server.jar"
        mode: 0555
      when: False #vagrant
    - name: Install Composer
      get_url:
        url: https://getcomposer.org/download/1.0.0-beta1/composer.phar
        dest: "{{ root }}/composer.phar"
        mode: 0555
      when: vagrant
    - name: Install Behat
      shell: "{{ composer }} install"
      args:
        chdir: "{{ root }}"
        creates: "{{ root }}/bin/behat"
    - name: Install drush-bde-env
      git:
        repo: https://github.com/pfrenssen/drush-bde-env.git
        dest: ~/.drush/drush-bde-env
      notify: Clear Drush cache
    - meta: flush_handlers
    - name: Generate Behat parameters
      shell: "{{ drush }} beg --subcontexts=profiles/{{ profile }}/modules --site-root={{ drupal_dir }} --skip-path-check --base-url={{ uri }} {{root}}/behat_params.sh"
      args:
        chdir: "{{ drupal_dir }}"
        creates: "{{ root }}/behat_params.sh"
        executable: /bin/bash


  handlers:
    - name: Clear Drush cache
      shell: "{{ drush }} cc drush"
      args:
        executable: /bin/bash
