---
- hosts: localhost
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Build platform
      shell: "{{ drush }} make -y {{ root }}/{{ makefile }} {{ drupal_dir }}"
      args:
        creates: "{{ drupal_dir }}"
        executable: /bin/bash
    - name: Symlink project root into platform as a profile
      file:
        state: link
        path: "{{ drupal_dir }}/profiles/{{ profile }}"
        src: "{{ root }}"
    - name: Install Drupal site
      shell: "{{ drush }} -y si {{ profile }} --db-url=mysql://root@localhost/site0 --account-pass=pwd"
      args:
        chdir: "{{ drupal_dir }}"
        creates: "{{ site_dir }}/settings.php"
        executable: /bin/bash
    - name: Generate a site alias
      copy:
        dest: "~/.drush/local.alias.drushrc.php"
        content: "<?php\n$aliases['local'] = array('root' => '{{ drupal_dir }}','uri' => '{{ uri }}');"
    - name: Check if PHP server is running
      shell: ps aux|grep [p]hp
      register: php
      changed_when: False
      failed_when: False
    - name: Run PHP server
      shell: "php -S 0.0.0.0:{{ port }} > ~/runserver.log &"
      args:
        chdir: "{{ drupal_dir }}"
      when: php.rc == 1
