---
- hosts: localhost
  vars:
    drush_version: master
  roles:
    - geerlingguy.mysql
    - geerlingguy.drush
  tasks:
    - name: Install some utilities
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - screen
        - htop
        - strace
        - tree
        - subversion
        - unzip
        - bzr
    - name: Make DB accessible
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "export UNISH_DB_URL='mysql://root:root@127.0.0.1'"
 
