---
- hosts: localhost
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Install some utilities
      apt:
        name: "{{ item }}"
        state: installed
      with_items: "{{ utilities }}"
      remote_user: root
      become: true
      when: vagrant
    - name: Install Drush dependencies
      apt:
        name: "{{ item }}"
        state: installed
      with_items: "{{ drush_deps }}"
      remote_user: root
      become: true
      when: vagrant
    - name: Create writeable binary directory
      file:
        state: directory
        dest: ~/bin
    - name: Download Drush
      get_url:
        url: http://files.drush.org/drush.phar
        dest: ~/bin/drush
        mode: 0555
    - name: Add local binaries to $PATH
      lineinfile:
        dest: ~/.bashrc
        line: "export PATH=\"$PATH:$HOME/bin\""
    - name: Refresh $PATH
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
